[google]
type = "service_account"
project_id = "studious-plate-459405-q4"
private_key_id = "322b16ab1d4528096299375f6e4b82c974a44694"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8q/PXDV9iB1Bc
IRVOAq0FwBLCLqspWwd8spPhFQHshgR2yJTh/uSOYD7RLEvky4LMIn9JWJwkiq0n
nDtxzJztOC5cxWE5nJ2YkLlfGUEYtz10+hTNn3Jfm8OkzKpT4Jko4exUX286XYxc
lM6ZOBPAGuh+HNc5aDdIO5gAEVjpAeVBu0/vwVrgWLumyFtveADtQsvlqf9kZco+
302G1jGy7wdBK0T9dnhfXqw8ZgnNV31p1B2RGUsnAhQjL9oRI8ym4YaYE55wUN0E
0QLMtUTpw70GdtPGAlezHD/D1l5VDVlcPQREUr8oO9w8e0z9R47s+CVsBSTalxGx
1cuCInrHAgMBAAECggEACYioNgoUniUqeA1VQJo9WK4KWfT2bIzksEtsfOeNL6uH
VuKZ4LWlolWAtxyFlUEnZzNTD/IXVHgMJJVDd7j+27SGuzoKHgQo/ohJpbbmpYi/
j/AB1HDQhxOdlkVKp28RA5IvBAXH3sDSvUGTvbBUvH9fl4fTjwYSImdIg1sHuCEX
DfAk6hHZKoAdYm0cJKBMexHZwx1FJp4nyBQu9gzl6hqymF+9AFOBnNHEkhyKiUZo
CmXO9WyVn8jvLVWiJqta7wZgrGJo5WrMFx67gXjCl1LI5TIrW0tYHIz4wiyoODZu
FD9Y0BXbP0uLj+cIvKyNr6W2mpEn/XLyWQpJ4et0KQKBgQD0e5eGBIAVcLGDIGJX
bhg8FoM8mWSpnMfRiedqtn8OTHWB0knhJVfURvPwQO9mWLJ4RQG0OicQ5eNzeBDi
EEYpdgSh9ZYJYD9xhjQ8Ck2Mc3dQ7eNiSJfuV7EQFRTvN4XSmUuFwV+IOxYXsAiD
KPvdqBW3CnssGhoHD1ZLOl5NNQKBgQDFj0qN8QT7nHDwBmYgUYdDH2MRRZg1ZhA+
xsAl178c4YTHcaM1tyZMdfMDoA64PQr1KElToBwR+hzg3DkCB4AbPOx64Kk8if9r
tQVydUnMtXokg/GvEGqjSmFEhGnLS7TAZwyfaLFaWE4HEkpItIcVnjCDVYYqpHvs
aRcmE/kziwKBgBx1qqzaJ0LXrIJUKb59vWp5QGu0e4hXDNeykvLULbQvaFplbV49
J505aTolhPjICHaBqfId9uA7sp+FcYmvVUuMRnvIB+AtiRUhB0GZ/W8FHfWYy6hs
ROtk3+K8YYR7VSOv3p/CY+mK30aAom0KP0+NOoHlQXNf0nnR6jy1nbalAoGBAIMR
AH5Q02R2MnsbU6/HRvyiGyB/Um7Cyq5LP3kbvD/V4jhLTOM7Id6CNfpGut1CKj3h
P1yKkXTfwT7w+6U8AqKPdbhDyiNOzjTPwNBhvddg4qrNGo9xTb4Nf6BsVJ+6Fy26
cCZl15u/j+yjFsNLeX8/FqJbIAq0Wz7JrcDmaWLnAoGAeOCKens081yiaYdGal/h
5MmvDThT+HrKoUIvocyo2dW+hENEHKl1LFAQmNUxkAsgmLrTemLdJoCTvzHM8PdW
ejNemt/8eqIqa38O5PDMG2WxegRzWa+XSo0E3Z0DWp+CIYNcDnCmewPN27jhXCf2
giCvUOg4QtN90exBowdZig0=
-----END PRIVATE KEY-----"""
client_email = "streamlit-anket@studious-plate-459405-q4.iam.gserviceaccount.com"
client_id = "106376877980451291256"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-anket%40studious-plate-459405-q4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"